### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by wwb568109135** [vczero/toilet#1]
Application toilet has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

runApplication
    AppRegistry.js:93
__callFunction
    MessageQueue.js:204
<unknown>
    MessageQueue.js:95
guard
    MessageQueue.js:41
callFunctionReturnFlushedQueue
    MessageQueue.js:94

**Comment by vczero** [comment]
你把服务重启下，在跟目录npm start,然后刷新模拟器
