### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by liucyu** [vczero/toilet#2]
![qq20160813-0 2x](https://cloud.githubusercontent.com/assets/13191643/17644010/dc8f7d9c-61ad-11e6-84d1-e7099cd209f3.png)
进行到此处再也没有任何反应了

**Comment by vczero** [comment]
把界面在模拟器里面cmd + r 刷新后即可。

**Comment by liucyu** [comment]
没有界面出来 也没有模拟器

**Comment by vczero** [comment]
说下你的执行流程，然后我再看看。如果不行，我再想办法跟你协助

**Comment by liucyu** [comment]
谢谢回复，我是直接cd进toilet目录执行npm start 然后并没有调出执行界面

**Comment by vczero** [comment]
确保电脑安装了xcode;
1) cd toilet
2) npm install
3)打开toilet/toilet/ios 下的心.xcodeproj文件，这时候应该启动了xcode
4)在xcode中，cmd + R(或者按xcode的运行按钮)运行程序
5）这时候应该启动了react packager命令行和模拟器。
6）如果模拟器是红色报错，则在模拟器上cmd + R刷新即可。

**Comment by vczero** [comment]
@liucyu 没问题了，就回复下，明天，我把这个issues关了，再补一篇如何启动项目。

**Comment by liucyu** [comment]
![image](https://cloud.githubusercontent.com/assets/13191643/17648704/874151cc-6251-11e6-9b68-dbeeb4f65905.png)
可是可以了，但是无论怎么刷新都是显示错误，另外，能把Android端怎么启动一并讲解一下吗？^-^

**Comment by vczero** [comment]
看原因npm packager没有启动。
1）在项目根目录, npm start启动
2）在模拟器上刷新

android这块代码需要小部分修改下，所以没有做适配，你可以适配完提交给我。：）
